version: '3'
services:
  web:
    build: ./docker/web
    privileged: true
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./docker/web/httpd-laravel.conf:/etc/httpd/conf.d/httpd-laravel.conf
      - ./docker/web/php-laravel.ini:/etc/php.d/php-laravel.ini
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d
      - ./db/data/:/var/lib/mysql
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025